Migration auth UI
brainlife/warehouse pull request #285
Opened 2021-09-21 13:41 UTC by bhatiadheeraj

2021-09-21 15:39 UTC, soichih requested changes
I've reviewed some changes.

Can you remove all those ui/images/*.png ? I don't think you need them, right?

2021-09-21 15:39 UTC, soichih commented on ui/src/settings.vue
> +.well{
Please add space between well and {

2021-09-21 15:39 UTC, soichih commented on ui/images/account.html
> +<div class="fixed-top">
What is this file for?

2021-09-21 15:39 UTC, soichih commented on ui/src/settings.vue
> +            <div v-if="tabs[tab].id == 'profile'">
Do you think we should create a simple computed property like this?

```
computed: {
tabID() {
     return this.tabs[tab].id; 
}
```

And use this in the template?

```
<div v-if="tabID == 'profile'">
```

Maybe it's silly?

2021-09-21 15:39 UTC, soichih commented on ui/src/settings.vue
> +            const jwt = localStorage.getItem("jwt");
You can use `Vue.config.jwt` to access the jwt. You don't need to do this.

2021-09-21 22:22 UTC, bhatiadheeraj commented
> I've reviewed some changes.
> 
> Can you remove all those ui/images/*.png ? I don't think you need them, right?

In which folder should I store the cilogon.png for OpenID connect

2021-09-22 21:28 UTC, soichih requested changes

2021-09-22 21:28 UTC, soichih commented on ui/src/settings.vue
> +            window.location = "api/auth/"+type+"/associate/"+this.jwt;
The URL is wrong. This needs to be

```
window.location = Vue.config.auth_api+"/"+type+"/associate/"+this.jwt;
```

2021-09-27 21:23 UTC, merged